# Site settings
title: Zhen Zhang
email: yuisheng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright - Zhen Zhang 2018
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yuisheng.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
